name: first workflow

on: 
 push:
   branches: 
    - master

jobs:
  example-job:
   runs-on: windows-latest

   steps:
     - name: Welcome message
       run: echo "welcome to our first Github"
       
     - name: Checkout repository
       uses: actions/checkout@v6.0.2

     - name: list repository files
       run: ls -la
    
